version: '3.9'

services:
    app:
        image: node:20.2-alpine
        command: sh -c "yarn install && yarn run start:dev"
        ports:
            - 3000:3000
        working_dir: /app
        volumes:
            - ./:/app
        networks:
            - backend

    mongo:
        image: mongo:4.2.8
        ports:
            - 27017:27017
        networks:
            - backend
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb

networks:
    backend:
        driver: bridge

volumes:
    mongodb:
    mongodb_config:
